version: '3'

services:
  nginx:
    image: nginx:mainline
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - 443:443
      - 80:80
    extra_hosts:
      - "dockerhost:${LOCAL_IP}"
