version: '3'

services:
  nginx:
    image: nginx:mainline
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/local.template
      - ./ssl:/etc/nginx/ssl
    ports:
      - 443:443
      - 80:80
    extra_hosts:
      - "dockerhost:${LOCAL_IP}"
    command: /bin/bash -c "printenv && envsubst '$$PROXY_PORT' < /etc/nginx/conf.d/local.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    env_file:
      - .env
